# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: book.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='book.proto',
  package='bookstore',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nbook.proto\x12\tbookstore\x1a\x1bgoogle/protobuf/empty.proto\"/\n\x0e\x41\x64\x64\x42ookRequest\x12\x1d\n\x04\x62ook\x18\x01 \x01(\x0b\x32\x0f.bookstore.Book\"f\n\x0f\x41\x64\x64\x42ookResponse\x12\x31\n\x06status\x18\x01 \x01(\x0e\x32!.bookstore.AddBookResponse.Status\" \n\x06Status\x12\x0b\n\x07SUCCESS\x10\x00\x12\t\n\x05\x45RROR\x10\x01\"5\n\x13GetAllBooksResponse\x12\x1e\n\x05\x62ooks\x18\x01 \x03(\x0b\x32\x0f.bookstore.Book\"F\n\x04\x42ook\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0c\n\x04year\x18\x02 \x01(\t\x12!\n\x06\x61uthor\x18\x03 \x01(\x0b\x32\x11.bookstore.Author\"\x16\n\x06\x41uthor\x12\x0c\n\x04name\x18\x01 \x01(\t2\x94\x01\n\tBookstore\x12@\n\x07\x41\x64\x64\x42ook\x12\x19.bookstore.AddBookRequest\x1a\x1a.bookstore.AddBookResponse\x12\x45\n\x0bGetAllBooks\x12\x16.google.protobuf.Empty\x1a\x1e.bookstore.GetAllBooksResponseb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])



_ADDBOOKRESPONSE_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='bookstore.AddBookResponse.Status',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=173,
  serialized_end=205,
)
_sym_db.RegisterEnumDescriptor(_ADDBOOKRESPONSE_STATUS)


_ADDBOOKREQUEST = _descriptor.Descriptor(
  name='AddBookRequest',
  full_name='bookstore.AddBookRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='book', full_name='bookstore.AddBookRequest.book', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=101,
)


_ADDBOOKRESPONSE = _descriptor.Descriptor(
  name='AddBookResponse',
  full_name='bookstore.AddBookResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='bookstore.AddBookResponse.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ADDBOOKRESPONSE_STATUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=205,
)


_GETALLBOOKSRESPONSE = _descriptor.Descriptor(
  name='GetAllBooksResponse',
  full_name='bookstore.GetAllBooksResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='books', full_name='bookstore.GetAllBooksResponse.books', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=207,
  serialized_end=260,
)


_BOOK = _descriptor.Descriptor(
  name='Book',
  full_name='bookstore.Book',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='bookstore.Book.title', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='year', full_name='bookstore.Book.year', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='author', full_name='bookstore.Book.author', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=262,
  serialized_end=332,
)


_AUTHOR = _descriptor.Descriptor(
  name='Author',
  full_name='bookstore.Author',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='bookstore.Author.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=334,
  serialized_end=356,
)

_ADDBOOKREQUEST.fields_by_name['book'].message_type = _BOOK
_ADDBOOKRESPONSE.fields_by_name['status'].enum_type = _ADDBOOKRESPONSE_STATUS
_ADDBOOKRESPONSE_STATUS.containing_type = _ADDBOOKRESPONSE
_GETALLBOOKSRESPONSE.fields_by_name['books'].message_type = _BOOK
_BOOK.fields_by_name['author'].message_type = _AUTHOR
DESCRIPTOR.message_types_by_name['AddBookRequest'] = _ADDBOOKREQUEST
DESCRIPTOR.message_types_by_name['AddBookResponse'] = _ADDBOOKRESPONSE
DESCRIPTOR.message_types_by_name['GetAllBooksResponse'] = _GETALLBOOKSRESPONSE
DESCRIPTOR.message_types_by_name['Book'] = _BOOK
DESCRIPTOR.message_types_by_name['Author'] = _AUTHOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AddBookRequest = _reflection.GeneratedProtocolMessageType('AddBookRequest', (_message.Message,), {
  'DESCRIPTOR' : _ADDBOOKREQUEST,
  '__module__' : 'book_pb2'
  # @@protoc_insertion_point(class_scope:bookstore.AddBookRequest)
  })
_sym_db.RegisterMessage(AddBookRequest)

AddBookResponse = _reflection.GeneratedProtocolMessageType('AddBookResponse', (_message.Message,), {
  'DESCRIPTOR' : _ADDBOOKRESPONSE,
  '__module__' : 'book_pb2'
  # @@protoc_insertion_point(class_scope:bookstore.AddBookResponse)
  })
_sym_db.RegisterMessage(AddBookResponse)

GetAllBooksResponse = _reflection.GeneratedProtocolMessageType('GetAllBooksResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETALLBOOKSRESPONSE,
  '__module__' : 'book_pb2'
  # @@protoc_insertion_point(class_scope:bookstore.GetAllBooksResponse)
  })
_sym_db.RegisterMessage(GetAllBooksResponse)

Book = _reflection.GeneratedProtocolMessageType('Book', (_message.Message,), {
  'DESCRIPTOR' : _BOOK,
  '__module__' : 'book_pb2'
  # @@protoc_insertion_point(class_scope:bookstore.Book)
  })
_sym_db.RegisterMessage(Book)

Author = _reflection.GeneratedProtocolMessageType('Author', (_message.Message,), {
  'DESCRIPTOR' : _AUTHOR,
  '__module__' : 'book_pb2'
  # @@protoc_insertion_point(class_scope:bookstore.Author)
  })
_sym_db.RegisterMessage(Author)



_BOOKSTORE = _descriptor.ServiceDescriptor(
  name='Bookstore',
  full_name='bookstore.Bookstore',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=359,
  serialized_end=507,
  methods=[
  _descriptor.MethodDescriptor(
    name='AddBook',
    full_name='bookstore.Bookstore.AddBook',
    index=0,
    containing_service=None,
    input_type=_ADDBOOKREQUEST,
    output_type=_ADDBOOKRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetAllBooks',
    full_name='bookstore.Bookstore.GetAllBooks',
    index=1,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_GETALLBOOKSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_BOOKSTORE)

DESCRIPTOR.services_by_name['Bookstore'] = _BOOKSTORE

# @@protoc_insertion_point(module_scope)
